on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-erlang@v1
        with:
          otp-version: 23.0
      - run: rebar3 eunit
